In [29]:
import pandas as pd
import numpy as np

In [30]:
data = pd.read_csv("maternal_data.csv")

In [31]:
data.head()

,study_id,TNFa1,TNFa2,TNFa3,TNFa4,TNFa5,TNFaAv,FOXP3.1,FOXP3.2,FOXP3.3,...,ehm_total_t2,acculturation_data_entered_t2,acculturation_data_verify_t2,acculturation_and_acculturative_stresspostpartum_f_complete,complete_study,withdraw_date,withdraw_reason,complete_study_date,study_comments,completion_data_complete
0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,EAC,HS,2.0,1.0,NaN,NaN,9/7/16,NaN,2.0
1,2.0,24.5,19.0,6.5,12.5,19.5,16.4,98.5,92.0,100.0,...,0.0,EAC,HS,2.0,1.0,NaN,NaN,8/19/16,NaN,2.0
2,3.0,23.5,17.5,9.0,14.5,28.0,18.5,98.5,90.5,99.0,...,0.0,EAC,HS,2.0,1.0,NaN,NaN,7/1/17,NaN,2.0
3,4.0,24.0,21.0,8.5,13.0,24.0,18.1,100.0,88.0,100.0,...,0.0,EAC,HS,2.0,1.0,NaN,NaN,9/6/16,NaN,2.0
4,5.0,33.0,28.5,7.0,13.5,22.5,20.9,99.5,90.0,99.0,...,4.0,EAC,HS,2.0,1.0,NaN,NaN,9/15/16,NaN,2.0

Next, we will replace all the NaN values with the respective column means.

In [32]:
df = data.dropna(how='all')

In [33]:
df = df[df.complete_study != 0]

In [6]:
df['what_was_your_due_date'] = pd.to_datetime(X['what_was_your_due_date'])
df['babys_date_of_birth'] = pd.to_datetime(X['babys_date_of_birth'])

In [ ]:
df['premature_birth_weeks'] = df['what_was_your_due_date'].sub(df['babys_date_of_birth'], axis=0)
df['premature_birth_weeks'] = df['premature_birth_weeks']/np.timedelta64(1, 'W')

df['premature_birth'] = np.where(df['premature_birth_weeks'] > 1, 1, 0)
export_with_target = df.to_csv('maternal_with_target.csv', index=False)

# Cluster ( detect outlier and drop patient)

prenatal_features = ['TNFa1', 'TNFa2', 'TNFa3', 'TNFa4', 'TNFa5', 'TNFaAv', 'FOXP3.1', 'FOXP3.2', 'FOXP3.3', 'FOXP3.4', 'FOXP3.5', 'FOXP3.6',
                     'FOXP3.7', 'FOXP3.av', 'total_score_phq', 'epds_score', 'idas_total', 'idas_gen_depression',
                     'idas_dysphoria', 'idas_lassitude', 'idas_suicidality', 'idas_appet_gain', 'idas_appet_loss', 'idas_well_being',
                     'idas_ill_temper', 'idas_mania', 'idas_euphoria', 'idas_panic', 'idas_social_anxiety',
                     'idas_claustrohobia', 'idas_traumatic_intrusions', 'idas_traumatic_avoidance', 'idas_checking', 'idas_cleaning',
                     'idas_ordering', 'total_score_gad_7', 'bas_total', 'acs_total', 'eds_total', 'ehm_total', 'premature_birth']


df_prenatal = df[prenatal_features]
export_prenatal_features = df_prenatal.to_csv('prenatal_features.csv', index=False)

In [25]:
# (X['what_was_your_due_date'] - X['babys_date_of_birth']).apply(lambda x: x/np.timedelta64(7,'W'))

In [26]:
# X['pre_birth'] = X['what_was_your_due_date'] - X['babys_date_of_birth']

In [27]:
# X['pre_birth'].apply(lambda x: x/np.timedelta64(1,'W'))

In [28]:
# X['pre_birth'].to_string()